#!/bin/bash

# if [ -f ~/.bash_dotfiles ]; then
#     source ~/.bash_dotfiles
# fi

#aliases
export LS_OPTIONS='-G --color'
alias ls='ls $LS_OPTIONS -hF'
alias ll='ls $LS_OPTIONS -lhtr'
alias lS='ls $LS_OPTIONS -lhSr'
alias cd..="cd .."
alias ..="cd .."

alias dope='python ~/dope/dope.py'
alias pygrep='grep --include="*.py" -R'
alias rmpyc='find . -name "*.pyc" -exec rm -rf {} \;'


# MacOS specific
if [ "$(uname)" == "Darwin" ]; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        source $(brew --prefix)/etc/bash_completion
    fi

		export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
		export PATH="/usr/local/bin:$PATH"
fi

# never hurts
export CLICOLOR=1
export SVN_EDITOR=vim

# git 
if [ -e ~/.git-prompt.sh ]; then
    source ~/.git-prompt.sh
fi
if [ -e ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
    export GIT_PS1_SHOWDIRTYSTATE=0
    export PS1='\[\e[0;35m\][\D{%F %T}] \[\e[0;36m\]\u\[\e[0;0m\]@\[\033[00m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")\$ '
else
    export PS1='\[\e[0;35m\][\D{%F %T}] \[\e[0;36m\]\u\[\e[0;0m\]@\[\033[00m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$\$ '
fi

# python
export PYTHONSTARTUP=~/.pythonrc.py
